.git
.gitignore
.DS_Store

node_modules
.next
out
build
coverage
*.tsbuildinfo
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

__pycache__
*.py[cod]
*$py.class
.pytest_cache
.mypy_cache
.ruff_cache

.env
.env.*
!.env.example

SCR-*.png
docs/*.png
